### ISSUE TITLE
Axios version needs bumping due to vulnerability in axio

### ISSUE THREAD

**Issue by webnoob** [sohaibilyas/facebook-js-sdk#1]
![image](https://user-images.githubusercontent.com/10404747/127821415-e12b662a-5217-4f59-ba89-c6270459c284.png)

Can you bump to `"axios": "^0.21.1",` and publish a new version please?

**Alternatively**, you could make Axios a peerDependency instead so the consuming project can handle version on it.

**Comment by sohaibilyas** [comment]
Released v1.0.0.
