### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by navasshareif** [sohaibilyas/facebook-js-sdk#1]
Bro... may i know how to control the quality of image while posting on user timeline

**Comment by sohaibilyas** [comment]
No matter how high resolution or high quality image you post to Facebook using it's API they will compress it for sure just like live Facebook web but the more high quality image you post the more quality your image will get on Facebook platform.

**Comment by navasshareif** [comment]
Thank you.

**Comment by navasshareif** [comment]
just check this bro postoo.in/votee

**Comment by jimosity** [comment]
I'm trying to retrieve a full list of all events from a page; not a user - I can't seem to get the api call right - any ideas?

**Comment by sohaibilyas** [comment]
Please head over to https://developers.facebook.com/docs/graph-api/reference/page/events/
